server:
  port: 8762
spring:
  application:
    name: springboot-conf-config-server

  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_ADDR:file:///C:/E/TOOLS/JAVA_21/WKS_DEMO/springboot-config-repo}
          default-label: ${CONFIG_REPO_BRANCH:master}
          #uri: file:///C:/E/TOOLS/JAVA_21/spring-boot-conf-config-server-repo
          #default-label: main

          search-paths: '{application}'

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_ADDR:http://localhost:8761/eureka/}